/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.if22.ui.internal.If22Activator;

public class If22UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return If22Activator.getInstance().getInjector("org.xtext.example.if22.If22");
	}

}
