/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.if22.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.if22.if22.EXPBOOL;
import org.xtext.example.if22.if22.If22Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EXPBOOL</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EXPBOOLImpl extends ExpressionImpl implements EXPBOOL
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EXPBOOLImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return If22Package.Literals.EXPBOOL;
  }

} //EXPBOOLImpl
