/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.if22.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.if22.if22.If22Package;
import org.xtext.example.if22.if22.TypeBoolean;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TypeBooleanImpl extends TypeImpl implements TypeBoolean
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeBooleanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return If22Package.Literals.TYPE_BOOLEAN;
  }

} //TypeBooleanImpl
