/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class If22Validator extends AbstractIf22Validator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					If22Package.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
