/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.if22.If22RuntimeModule;
import org.xtext.example.if22.If22StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class If22IdeSetup extends If22StandaloneSetup {
  @Override
  public Injector createInjector() {
    If22RuntimeModule _if22RuntimeModule = new If22RuntimeModule();
    If22IdeModule _if22IdeModule = new If22IdeModule();
    return Guice.createInjector(Modules2.mixin(_if22RuntimeModule, _if22IdeModule));
  }
}
