/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIf22ScopeProvider extends DelegatingScopeProvider {
}
