/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class If22UiModule extends AbstractIf22UiModule {

	public If22UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
