/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class If22UiModule extends AbstractIf22UiModule {
}
