/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class If22StandaloneSetup extends If22StandaloneSetupGenerated {

	public static void doSetup() {
		new If22StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
