/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.if22.ui.internal.If22Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class If22ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(If22Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		If22Activator activator = If22Activator.getInstance();
		return activator != null ? activator.getInjector(If22Activator.ORG_XTEXT_EXAMPLE_IF22_IF22) : null;
	}

}
