/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.scoping;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.xtext.example.if22.if22.EndingTarget;
import org.xtext.example.if22.if22.Program;
import org.eclipse.xtext.EcoreUtil2;
/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class If22ScopeProvider extends AbstractIf22ScopeProvider {


		
}
