/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.if22;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ending Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.if22.if22.EndingTarget#getCallableEnd <em>Callable End</em>}</li>
 *   <li>{@link org.xtext.example.if22.if22.EndingTarget#getSelfdefinedEnd <em>Selfdefined End</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.if22.if22.If22Package#getEndingTarget()
 * @model
 * @generated
 */
public interface EndingTarget extends EObject
{
  /**
   * Returns the value of the '<em><b>Callable End</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Callable End</em>' reference.
   * @see #setCallableEnd(End)
   * @see org.xtext.example.if22.if22.If22Package#getEndingTarget_CallableEnd()
   * @model
   * @generated
   */
  End getCallableEnd();

  /**
   * Sets the value of the '{@link org.xtext.example.if22.if22.EndingTarget#getCallableEnd <em>Callable End</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Callable End</em>' reference.
   * @see #getCallableEnd()
   * @generated
   */
  void setCallableEnd(End value);

  /**
   * Returns the value of the '<em><b>Selfdefined End</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selfdefined End</em>' reference.
   * @see #setSelfdefinedEnd(End)
   * @see org.xtext.example.if22.if22.If22Package#getEndingTarget_SelfdefinedEnd()
   * @model
   * @generated
   */
  End getSelfdefinedEnd();

  /**
   * Sets the value of the '{@link org.xtext.example.if22.if22.EndingTarget#getSelfdefinedEnd <em>Selfdefined End</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selfdefined End</em>' reference.
   * @see #getSelfdefinedEnd()
   * @generated
   */
  void setSelfdefinedEnd(End value);

} // EndingTarget
