/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.if22;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EXPINT</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.if22.if22.If22Package#getEXPINT()
 * @model
 * @generated
 */
public interface EXPINT extends Expression
{
} // EXPINT
