/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.if22.if22;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.if22.if22.If22Factory
 * @model kind="package"
 * @generated
 */
public interface If22Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "if22";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/if22/If22";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "if22";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  If22Package eINSTANCE = org.xtext.example.if22.if22.impl.If22PackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.ProgramImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Scenarios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__SCENARIOS = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.ScenarioImpl <em>Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.ScenarioImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getScenario()
   * @generated
   */
  int SCENARIO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__NAME = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.StatementImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.AnnouncementImpl <em>Announcement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.AnnouncementImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getAnnouncement()
   * @generated
   */
  int ANNOUNCEMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCEMENT__NAME = STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCEMENT__EXP = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCEMENT__TARGET = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Announcement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.QuestionImpl <em>Question</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.QuestionImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getQuestion()
   * @generated
   */
  int QUESTION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__NAME = STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>QString</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__QSTRING = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>QType</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__QTYPE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__TARGET = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Question</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.EndImpl <em>End</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.EndImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getEnd()
   * @generated
   */
  int END = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__NAME = STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__EXP = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>End</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.TargetImpl <em>Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.TargetImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getTarget()
   * @generated
   */
  int TARGET = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__NAME = 0;

  /**
   * The number of structural features of the '<em>Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.ExpressionImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 7;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.ExpImpl <em>Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.ExpImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getExp()
   * @generated
   */
  int EXP = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.LogicImpl <em>Logic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.LogicImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getLogic()
   * @generated
   */
  int LOGIC = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Logic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.MathImpl <em>Math</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.MathImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getMath()
   * @generated
   */
  int MATH = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Math</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.TextExpImpl <em>Text Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.TextExpImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getTextExp()
   * @generated
   */
  int TEXT_EXP = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_EXP__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_EXP__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Text Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_EXP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.TypeImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getType()
   * @generated
   */
  int TYPE = 12;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.ThisImpl <em>This</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.ThisImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getThis()
   * @generated
   */
  int THIS = 13;

  /**
   * The number of structural features of the '<em>This</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THIS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.EXPSTRINGImpl <em>EXPSTRING</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.EXPSTRINGImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getEXPSTRING()
   * @generated
   */
  int EXPSTRING = 14;

  /**
   * The number of structural features of the '<em>EXPSTRING</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPSTRING_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.EXPINTImpl <em>EXPINT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.EXPINTImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getEXPINT()
   * @generated
   */
  int EXPINT = 15;

  /**
   * The number of structural features of the '<em>EXPINT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPINT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.EXPBOOLImpl <em>EXPBOOL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.EXPBOOLImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getEXPBOOL()
   * @generated
   */
  int EXPBOOL = 16;

  /**
   * The number of structural features of the '<em>EXPBOOL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPBOOL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.IDImpl <em>ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.IDImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getID()
   * @generated
   */
  int ID = 17;

  /**
   * The number of structural features of the '<em>ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.if22.if22.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.if22.if22.impl.ParenthesisImpl
   * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getParenthesis()
   * @generated
   */
  int PARENTHESIS = 18;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__EXP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parenthesis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.if22.if22.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.if22.if22.Program#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.if22.if22.Program#getName()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.if22.if22.Program#getScenarios <em>Scenarios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scenarios</em>'.
   * @see org.xtext.example.if22.if22.Program#getScenarios()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Scenarios();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Scenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario</em>'.
   * @see org.xtext.example.if22.if22.Scenario
   * @generated
   */
  EClass getScenario();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.if22.if22.Scenario#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.if22.if22.Scenario#getName()
   * @see #getScenario()
   * @generated
   */
  EAttribute getScenario_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.if22.if22.Scenario#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.if22.if22.Scenario#getStatements()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.example.if22.if22.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.if22.if22.Statement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.if22.if22.Statement#getName()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Announcement <em>Announcement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Announcement</em>'.
   * @see org.xtext.example.if22.if22.Announcement
   * @generated
   */
  EClass getAnnouncement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.Announcement#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.example.if22.if22.Announcement#getExp()
   * @see #getAnnouncement()
   * @generated
   */
  EReference getAnnouncement_Exp();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.if22.if22.Announcement#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Target</em>'.
   * @see org.xtext.example.if22.if22.Announcement#getTarget()
   * @see #getAnnouncement()
   * @generated
   */
  EReference getAnnouncement_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Question <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question</em>'.
   * @see org.xtext.example.if22.if22.Question
   * @generated
   */
  EClass getQuestion();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.Question#getQString <em>QString</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>QString</em>'.
   * @see org.xtext.example.if22.if22.Question#getQString()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_QString();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.Question#getQType <em>QType</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>QType</em>'.
   * @see org.xtext.example.if22.if22.Question#getQType()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_QType();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.if22.if22.Question#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Target</em>'.
   * @see org.xtext.example.if22.if22.Question#getTarget()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.End <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End</em>'.
   * @see org.xtext.example.if22.if22.End
   * @generated
   */
  EClass getEnd();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.End#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.example.if22.if22.End#getExp()
   * @see #getEnd()
   * @generated
   */
  EReference getEnd_Exp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Target <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target</em>'.
   * @see org.xtext.example.if22.if22.Target
   * @generated
   */
  EClass getTarget();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.if22.if22.Target#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.if22.if22.Target#getName()
   * @see #getTarget()
   * @generated
   */
  EAttribute getTarget_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.if22.if22.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Exp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp</em>'.
   * @see org.xtext.example.if22.if22.Exp
   * @generated
   */
  EClass getExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.Exp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.if22.if22.Exp#getLeft()
   * @see #getExp()
   * @generated
   */
  EReference getExp_Left();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Logic <em>Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic</em>'.
   * @see org.xtext.example.if22.if22.Logic
   * @generated
   */
  EClass getLogic();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.Logic#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.if22.if22.Logic#getLeft()
   * @see #getLogic()
   * @generated
   */
  EReference getLogic_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.Logic#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.if22.if22.Logic#getRight()
   * @see #getLogic()
   * @generated
   */
  EReference getLogic_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Math <em>Math</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Math</em>'.
   * @see org.xtext.example.if22.if22.Math
   * @generated
   */
  EClass getMath();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.Math#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.if22.if22.Math#getLeft()
   * @see #getMath()
   * @generated
   */
  EReference getMath_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.Math#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.if22.if22.Math#getRight()
   * @see #getMath()
   * @generated
   */
  EReference getMath_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.TextExp <em>Text Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Exp</em>'.
   * @see org.xtext.example.if22.if22.TextExp
   * @generated
   */
  EClass getTextExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.TextExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.if22.if22.TextExp#getLeft()
   * @see #getTextExp()
   * @generated
   */
  EReference getTextExp_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.TextExp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.if22.if22.TextExp#getRight()
   * @see #getTextExp()
   * @generated
   */
  EReference getTextExp_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.if22.if22.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.This <em>This</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>This</em>'.
   * @see org.xtext.example.if22.if22.This
   * @generated
   */
  EClass getThis();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.EXPSTRING <em>EXPSTRING</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EXPSTRING</em>'.
   * @see org.xtext.example.if22.if22.EXPSTRING
   * @generated
   */
  EClass getEXPSTRING();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.EXPINT <em>EXPINT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EXPINT</em>'.
   * @see org.xtext.example.if22.if22.EXPINT
   * @generated
   */
  EClass getEXPINT();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.EXPBOOL <em>EXPBOOL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EXPBOOL</em>'.
   * @see org.xtext.example.if22.if22.EXPBOOL
   * @generated
   */
  EClass getEXPBOOL();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.ID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ID</em>'.
   * @see org.xtext.example.if22.if22.ID
   * @generated
   */
  EClass getID();

  /**
   * Returns the meta object for class '{@link org.xtext.example.if22.if22.Parenthesis <em>Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parenthesis</em>'.
   * @see org.xtext.example.if22.if22.Parenthesis
   * @generated
   */
  EClass getParenthesis();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.if22.if22.Parenthesis#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.example.if22.if22.Parenthesis#getExp()
   * @see #getParenthesis()
   * @generated
   */
  EReference getParenthesis_Exp();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  If22Factory getIf22Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.ProgramImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__NAME = eINSTANCE.getProgram_Name();

    /**
     * The meta object literal for the '<em><b>Scenarios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__SCENARIOS = eINSTANCE.getProgram_Scenarios();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.ScenarioImpl <em>Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.ScenarioImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getScenario()
     * @generated
     */
    EClass SCENARIO = eINSTANCE.getScenario();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENARIO__NAME = eINSTANCE.getScenario_Name();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__STATEMENTS = eINSTANCE.getScenario_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.StatementImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__NAME = eINSTANCE.getStatement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.AnnouncementImpl <em>Announcement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.AnnouncementImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getAnnouncement()
     * @generated
     */
    EClass ANNOUNCEMENT = eINSTANCE.getAnnouncement();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANNOUNCEMENT__EXP = eINSTANCE.getAnnouncement_Exp();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANNOUNCEMENT__TARGET = eINSTANCE.getAnnouncement_Target();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.QuestionImpl <em>Question</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.QuestionImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getQuestion()
     * @generated
     */
    EClass QUESTION = eINSTANCE.getQuestion();

    /**
     * The meta object literal for the '<em><b>QString</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__QSTRING = eINSTANCE.getQuestion_QString();

    /**
     * The meta object literal for the '<em><b>QType</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__QTYPE = eINSTANCE.getQuestion_QType();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__TARGET = eINSTANCE.getQuestion_Target();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.EndImpl <em>End</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.EndImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getEnd()
     * @generated
     */
    EClass END = eINSTANCE.getEnd();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference END__EXP = eINSTANCE.getEnd_Exp();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.TargetImpl <em>Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.TargetImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getTarget()
     * @generated
     */
    EClass TARGET = eINSTANCE.getTarget();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TARGET__NAME = eINSTANCE.getTarget_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.ExpressionImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.ExpImpl <em>Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.ExpImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getExp()
     * @generated
     */
    EClass EXP = eINSTANCE.getExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__LEFT = eINSTANCE.getExp_Left();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.LogicImpl <em>Logic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.LogicImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getLogic()
     * @generated
     */
    EClass LOGIC = eINSTANCE.getLogic();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC__LEFT = eINSTANCE.getLogic_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC__RIGHT = eINSTANCE.getLogic_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.MathImpl <em>Math</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.MathImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getMath()
     * @generated
     */
    EClass MATH = eINSTANCE.getMath();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MATH__LEFT = eINSTANCE.getMath_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MATH__RIGHT = eINSTANCE.getMath_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.TextExpImpl <em>Text Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.TextExpImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getTextExp()
     * @generated
     */
    EClass TEXT_EXP = eINSTANCE.getTextExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT_EXP__LEFT = eINSTANCE.getTextExp_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT_EXP__RIGHT = eINSTANCE.getTextExp_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.TypeImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.ThisImpl <em>This</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.ThisImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getThis()
     * @generated
     */
    EClass THIS = eINSTANCE.getThis();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.EXPSTRINGImpl <em>EXPSTRING</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.EXPSTRINGImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getEXPSTRING()
     * @generated
     */
    EClass EXPSTRING = eINSTANCE.getEXPSTRING();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.EXPINTImpl <em>EXPINT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.EXPINTImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getEXPINT()
     * @generated
     */
    EClass EXPINT = eINSTANCE.getEXPINT();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.EXPBOOLImpl <em>EXPBOOL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.EXPBOOLImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getEXPBOOL()
     * @generated
     */
    EClass EXPBOOL = eINSTANCE.getEXPBOOL();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.IDImpl <em>ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.IDImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getID()
     * @generated
     */
    EClass ID = eINSTANCE.getID();

    /**
     * The meta object literal for the '{@link org.xtext.example.if22.if22.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.if22.if22.impl.ParenthesisImpl
     * @see org.xtext.example.if22.if22.impl.If22PackageImpl#getParenthesis()
     * @generated
     */
    EClass PARENTHESIS = eINSTANCE.getParenthesis();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARENTHESIS__EXP = eINSTANCE.getParenthesis_Exp();

  }

} //If22Package
